# Default values for ltb-passwd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiredofit/self-service-password
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
ldap:
  server: ldap://openldap.openldap
  searchBase: dc=example,dc=org
  # existingSecret: ssp-ldap
  bindDN: cn=admin,dc=example,dc=org
  bindPWKey: BINDPW
env:
  - name: SECRETEKEY
    value: "password"
  - name: LDAP_LOGIN_ATTRIBUTE
    value: "cn"