# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hiveMetastore.labels" . | nindent 4 }}
spec:
  ports:
  - name: thrift
    port: 9083
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: metastore
    app.kubernetes.io/instance: {{ .Release.Name }}
