apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentsdb.fullname" . }}-grafana-datasource
  labels:
    app.kubernetes.io/name: {{ include "opentsdb.name" . }}
    {{- include "opentsdb.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: PNDA OpenTSDB
        orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
    - name: PNDA OpenTSDB
      type: opentsdb
      access: proxy
      orgId: 1
      url: http://{{ include "opentsdb.fullname" . }}:4242
      basicAuth: false
      isDefault: true
      # <map> fields that will be converted to json and stored in json_data
      jsonData:
         tsdbVersion: "2.3"
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: false
