apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-postgresql-init
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    {{- include "hiveMetastore.labels" . | nindent 4 }}
data:
  00-hive-schema-2.3.0.postgres.sql: |-
{{ tpl (.Files.Get "files/hive-schema-2.3.0.postgres.sql") . | indent 4 }}
  01-hive-txn-schema-2.3.0.postgres.sql: |-
{{ tpl (.Files.Get "files/hive-txn-schema-2.3.0.postgres.sql") . | indent 4 }}