auth:
  postgresPassword: adminpassword
  username: foo
  password: foopassword
  database: bar
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
  prometheusRule:
    enabled: true
    namespace: monitoring
networkPolicy:
  enabled: true
  metrics:
    enabled: true
    namespaceSelector:
      label: monitoring
  ingressRules:
    primaryAccessOnlyFrom:
      enabled: true
      podSelector:
        "{{ template \"common.names.fullname\" . }}-client": "true"
