serviceAccount:
  create: true
  name: custom-sa
  automountServiceAccountToken: true
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
psp:
  create: true
