image:
  registry: gethue/hue
  tag: 4.10.0
  pullPolicy: IfNotPresent

postgresql:
  name: postgresql
  enabled: true
  host: ~
  port: 5432
  auth:
    postgresPassword: "postgres"
    database: "hue"
    username: "hue"
    password: "hue"
    password_script: ~
hue:
  replicas: 1
#  interpreters: |-
#    [[[postgresql]]]
#    name = postgresql
#    interface=sqlalchemy
#    options='{"url": "postgresql://hue:hue@my-hue-postgres:5432/hue"}'
  ini: |
    [desktop]
    secret_key=hue123
    app_blacklist=filebrowser,search,hbase,security,jobbrowser,oozie
    django_debug_mode=false
    gunicorn_work_class=sync
    enable_prometheus=true

    [[task_server]]
    enabled=false
    broker_url=redis://redis:6379/0
    result_cache='{"BACKEND": "django_redis.cache.RedisCache", "LOCATION": "redis://redis:6379/0", "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},"KEY_PREFIX": "queries"}'
    celery_result_backend=redis://redis:6379/0

conf:
  hiveSite: {}
    # hive.support.concurrency: false
aws:
  accessKeyId: ""
  secretAccessKey: ""
  awsRegion: "us-east-1"