{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}-ltb-passwd
  labels:
    app.kubernetes.io/name: {{ include "openldap.name" . }}
    app.kubernetes.io/component: openldap
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
{{ end }}
