apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hue.fullname" . }}-config
data:
  z-hue-ini: |
    [desktop]

    [[database]]
    engine=postgresql_psycopg2
    host={{ .Values.postgresql.host | default (printf "%s-postgres" (include "hue.fullname" .)) }}
    port={{ .Values.postgresql.port }}
    user={{ .Values.postgresql.auth.user }}
{{- if .Values.postgresql.auth.password_script }}
    password_script={{ .Values.postgresql.auth.password_script }}
{{- else }}
    password={{ .Values.postgresql.auth.password }}
{{- end }}
    name={{ .Values.postgresql.name }}

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id={{ .Values.aws.accessKeyId }}
    secret_access_key={{ .Values.aws.secretAccessKey }}
    region={{ .Values.aws.region }}

    [notebook]
    [[interpreters]]
    [[[postgresql]]]
    name = postgresql
    interface=sqlalchemy
    options='{"url": "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.host | default (printf "%s-postgres" (include "hue.fullname" .)) }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.auth.database }}"}'
    {{- if .Values.hue.interpreters }}
    {{ .Values.hue.interpreters | indent 4 }}
    {{- end }}
