apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hue.fullname" . }}-config
data:
  hue-ini: |
    [desktop]

    [[database]]
    engine={{ .Values.hue.database.engine }}
    host={{ .Values.hue.database.host | default (printf "%s-postgres" (include "hue.fullname" .)) }}
    port={{ .Values.hue.database.port }}
    user={{ .Values.hue.database.user }}
{{- if .Values.hue.database.password_script }}
    password_script={{ .Values.hue.database.password_script }}
{{- else }}
    password={{ .Values.hue.database.password }}
{{- end }}
    name={{ .Values.hue.database.name }}

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id={{ .Values.aws.accessKeyId }}
    secret_access_key={{ .Values.aws.secretAccessKey }}
    region={{ .Values.aws.region }}

    [notebook]
    [[interpreters]]
    [[[postgresql]]]
    name = postgresql
    interface=sqlalchemy
    options='{"url": "postgresql://{{ .Values.hue.database.user }}:{{ .Values.hue.database.password }}@{{ .Values.hue.database.host | default (printf "%s-postgres" (include "hue.fullname" .)) }}:{{ .Values.hue.database.port }}/{{ .Values.hue.database.name }}"}'
    {{- if .Values.hue.interpreters }}
    {{ .Values.hue.interpreters | indent 4 }}
    {{- end }}
