{{- if .Values.hue.database.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hue.fullname" . }}-postgres
spec:
  ports:
    - name: pgql
      port: 5432
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "hue.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end -}}
